### ISSUE TITLE
Hello.Nice to meet your project.

### ISSUE THREAD

**Issue by Jiangzhiwei-king** [FreeTile/Binance#2]
May I ask if this neural network is really effective for virtual currency? I have a big question, can you communicate with me, and how can I contact you. I have a similar project but it doesn't work.

**Comment by FreeTile** [comment]
You can contact with me by writing there) I will answer you when I can. Now time it is bad for virtual currency, btw its bad just because half of my code from "Trading.py" doesn't work good with my current balance on binance. I am testing model today with more USDT at my account. Also I can check your project if you have repos with it.

**Comment by FreeTile** [comment]
I can’t give an exact answer which neural network will do the best and what data is best fed into them, while I work purely on errors, if it works well, it will be a big success

**Comment by FreeTile** [comment]
If you have another question, please create a new issue.
